exports.ROLES = {
    SUPER_ADMIN: 1,
    ADMIN: 2,
    USER: 3,
};

exports.GENDER = {
    MALE: 1,
    FEMALE: 2
};

exports.RESPONSES = {
    INVALID_INPUT: 'INVALID_INPUT',
    INVALID_MOBILE: 'INVALID_MOBILE',
    INVALID_OTP: 'INVALID_OTP',
    INVALID_ACCESS_TOKEN: 'INVALID_ACCESS_TOKEN',
    USER_NOT_FOUND: 'USER_NOT_FOUND',
    INVALID_USER_ROLE: 'INVALID_USER_ROLE',
    USER_ALREADY_EXIST: 'USER_ALREADY_EXIST',
    FIELD_IS_REQUIRED: 'FIELD_IS_REQUIRED',
    MOBILE_IS_REQUIRED: 'MOBILE_IS_REQUIRED',
    UNAUTHORIZED_ACCESS: 'UNAUTHORIZED_ACCESS',
    YOUR_ACTIVATION_CODE_IS: 'YOUR_ACTIVATION_CODE_IS',
    YOUR_DELETE_CODE_IS: 'YOUR_DELETE_CODE_IS',
    ITEM_NOT_FOUND: 'ITEM_NOT_FOUND',
    FILE_IS_REQUIRED: 'FILE_IS_REQUIRED'
}
